In [1]:
import torch

In [2]:
x = torch.empty(3)
print(x)

tensor([0., 0., 0.])


In [3]:
#2D matrix
x = torch.empty(2,3)
print(x)

tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [4]:
#3D matrix
x = torch.empty (2,2,3)
print(x)

tensor([[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]])


In [5]:
#4D matrix
x = torch.empty(2,2,2,3)
print(x)

tensor([[[[0., 0., 0.],
          [0., 0., 0.]],

         [[0., 0., 0.],
          [0., 0., 0.]]],


        [[[0., 0., 0.],
          [0., 0., 0.]],

         [[0., 0., 0.],
          [0., 0., 0.]]]])


In [6]:
x = torch.zeros(3)
print(x)

tensor([0., 0., 0.])


In [7]:
x = torch.ones(3)
print(x)
print(x.dtype)

tensor([1., 1., 1.])
torch.float32


In [8]:
x = torch.ones(3 , dtype=torch.int)
print(x)
print(x.dtype)

tensor([1, 1, 1], dtype=torch.int32)
torch.int32


In [9]:
x = torch.ones(3,3 , dtype=torch.double)
print(x)
print(x.dtype)
print(x.size())

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
torch.float64
torch.Size([3, 3])


In [10]:
x = torch.tensor([2.5,6.7])
print(x)

tensor([2.5000, 6.7000])


In [11]:
x = torch.rand(2,2)
y = torch.rand(2,2)
print(x)
print(y)

tensor([[0.2942, 0.5934],
        [0.5002, 0.6747]])
tensor([[0.5147, 0.9457],
        [0.9889, 0.9670]])


In [12]:
z = x + y
print(z)

tensor([[0.8089, 1.5391],
        [1.4892, 1.6417]])


In [13]:
z = torch.add(x,y)
print(z)

tensor([[0.8089, 1.5391],
        [1.4892, 1.6417]])


In [14]:
# inplace addition
y.add_(x)
print(y)

tensor([[0.8089, 1.5391],
        [1.4892, 1.6417]])


In [15]:
z = x - y
print(z)

tensor([[-0.5147, -0.9457],
        [-0.9889, -0.9670]])


In [16]:
z = torch.sub(x,y)
print(z)

tensor([[-0.5147, -0.9457],
        [-0.9889, -0.9670]])


In [17]:
z = x * y
z = torch.mul(x,y)
y.mul_(x)
print(z)

tensor([[0.2380, 0.9133],
        [0.7449, 1.1077]])


In [18]:
z = x / y
z = torch.div(x,y)
print(z)

tensor([[1.2363, 0.6497],
        [0.6715, 0.6091]])


In [19]:
#Slicing
x = torch.rand(5,3)
print(x)
print(x[:, 0])
print(x[1,:])
print(x[1,1].item())

tensor([[0.7759, 0.2438, 0.6031],
        [0.3120, 0.7402, 0.7623],
        [0.6354, 0.2052, 0.4184],
        [0.3947, 0.2526, 0.9863],
        [0.3143, 0.6415, 0.2976]])
tensor([0.7759, 0.3120, 0.6354, 0.3947, 0.3143])
tensor([0.3120, 0.7402, 0.7623])
0.7402431964874268


In [20]:
x = torch.rand(4,4)
print(x)

y = x.view(16)
print(y)

tensor([[0.9996, 0.0128, 0.9423, 0.3544],
        [0.4637, 0.2814, 0.6869, 0.3410],
        [0.0235, 0.2483, 0.2725, 0.2868],
        [0.5822, 0.4505, 0.0078, 0.4608]])
tensor([0.9996, 0.0128, 0.9423, 0.3544, 0.4637, 0.2814, 0.6869, 0.3410, 0.0235,
        0.2483, 0.2725, 0.2868, 0.5822, 0.4505, 0.0078, 0.4608])


In [21]:
import numpy as np 
a = torch.ones(5)
print(a)

b = a.numpy()
print(b)
print(type(b))

tensor([1., 1., 1., 1., 1.])
[1. 1. 1. 1. 1.]
<class 'numpy.ndarray'>


In [22]:
a.add_(1)
print(a)

tensor([2., 2., 2., 2., 2.])


In [23]:
a = np.ones(5)
print(a)
b = torch.from_numpy(a)
print(b)

[1. 1. 1. 1. 1.]
tensor([1., 1., 1., 1., 1.], dtype=torch.float64)


In [24]:
a = a +1
print(a)

[2. 2. 2. 2. 2.]
